name: task_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0

  # state management
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1

  #for api
  http: ^0.13.5

  # for video
  chewie: ^1.3.4
  video_player: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
